// pages/books/search.tsx
import { useState } from "react";
import { BooksNav } from "@/components/BooksNav";
import PageFrame from "@/components/PageFrame";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import React from "react";
import { useLoadingContext } from "@/lib/LoadingContext";
import { useRouter } from "next/router";

export default function OpenBookSearch() {
  const [isbn, setISBN] = useState("");
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState(false);
  const [results, setResults] = useState({});

  function reset() {
    setSearching(false);
    setError(false);
    setResults({});
  }

  async function search() {
    if (!isbn) {
      setError(true);
      return;
    }
    try {
      setResults({});
      setError(false);
      setSearching(true);
      const response = await fetch(`https://openlibrary.org/isbn/${isbn.trim()}.json`);
      if (!response.ok) {
        if (response.status === 404) {
          throw new Error("Book not found");
        }
        throw new Error("Something went wrong");
      }
      const body = await response.json();
      setResults(body);
      setSearching(false);
    } catch (error) {
      console.log(error);
      setSearching(false);
      setError(true);
    }
  }
  return (
    <PageFrame title="Books">
      <BooksNav />
      <div className="flex flex-col sm:flex-row justify-center items-center gap-5">
        <Input
          className="my-2 basis-full sm:basis-3/4"
          type="text"
          placeholder="Search OpenBooks by ISBN"
          onChange={(e) => setISBN(e.target.value)}
        />
        <div className="basis-full sm:basis-1/4 flex justify-around items-center gap-2">
          <Button onClick={search}>Search</Button>
          <Button variant="secondary" onClick={reset}>
            Reset
          </Button>
        </div>
      </div>
      {searching && <Searching />}
      {error && <SearchError />}
      {Object.keys(results).length !== 0 && <SearchResults data={results} isbn={isbn} />}
    </PageFrame>
  );
}

function Searching() {
  return (
    <div className="flex flex-col justify-center items-center py-10">
      <h2 className="text-xl py-5 ">Searching ... </h2>
    </div>
  );
}

function SearchError() {
  return (
    <div className="flex flex-col justify-center items-center py-10">
      <h2 className="text-xl py-5 text-accent">An Error Occured</h2>
      <p>Please use the reset button and try again</p>
    </div>
  );
}

function SearchResults(props: any) {
  const router = useRouter();
  const { setLoading } = useLoadingContext();
  async function submit() {
    try {
      setLoading(true);
      const response = await fetch(`/api/books/`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: props.data.title,
          author: props.data.by_statement,
          isbn: props.isbn,
          image: `https://covers.openlibrary.org/b/isbn/${props.isbn}-M.jpg`,
        }),
      });
      //Check for ok response
      if (!response.ok) {
        throw new Error("Something went wrong please try again");
      }
      router.push("/books");
      setLoading(false);
    } catch (error) {
      console.log(error);
      setLoading(false);
    }
  }
  return (
    <div className="py-5 flex w-full justify-center items-center">
      <img
        src={`https://covers.openlibrary.org/b/isbn/${props.isbn}-M.jpg`}
        alt={props.data.title}
        className="hidden sm:block basis-1/4 h-72"
      />
      <div className="basis-3/4 flex flex-col md:flex-row justify-center px-2">
        <div className="basis-full md:basis-3/4 text-center md:text-left flex flex-col justify-center items-center gap-2 px-2 lg:px-5">
          <div className="w-full">
            <span className="text-xl">Title / Name :</span> {props.data.title}
          </div>
          <div className="w-full">
            <span className="text-xl">Author :</span> {props.data.by_statement}
          </div>
          <div className="w-full">
            <span className="text-xl">ISBN :</span> {props.isbn}
          </div>
        </div>
        <div className="basis-full md:basis-1/4 flex justify-center items-center py-5">
          <Button type="submit" onClick={submit}>
            Add to Library
          </Button>
        </div>
      </div>
    </div>
  );
}

// _archive/src/routes/(app)/books/search/+page.svelte
<script lang="ts">
  import { Input } from "@/lib/components/ui/input";
  import { Button } from "@/lib/components/ui/button";
  import type { PageData } from "./$types";
  import { enhance } from "$app/forms";
  import { createBookFormSchema } from "@/lib/schema";
  import { toast } from "svelte-sonner";
  import { goto } from "$app/navigation";

  let { data }: { data: PageData } = $props();
  let searchisbn: string = $state("");
  let result: any = $state(null);
  let searching: boolean = $state(false);
  let error: boolean = $state(false);

  function clear() {
    searchisbn = "";
    result = null;
    searching = false;
    error = false;
  }

  async function search() {
    if (!searchisbn) {
      error = true;
      return;
    }
    try {
      searching = true;
      const response = await fetch(
        `https://openlibrary.org/isbn/${searchisbn.trim()}.json`,
      );
      if (!response.ok) {
        if (response.status === 404) {
          throw new Error("No books found");
        }
        throw new Error("Something went wrong");
      }
      const res = await response.json();
      console.log(res);

      result = res;
      searching = false;
    } catch (err) {
      console.log(err);
      result = null;
      searching = false;
      error = true;
    }
  }
</script>

<div class="w-full flex justify-between items-center gap-x-5">
  <Input
    class="my-2"
    type="text"
    placeholder="Search OpenBooks database by ISBN"
    name="search"
    bind:value={searchisbn}
  />
  <Button onclick={() => search()}>Search</Button>
  <Button variant="secondary" onclick={() => clear()}>Clear</Button>
</div>

{#if searching}
  <div class="w-full text-center py-5">
    <h2 class="text-lg">Searching...</h2>
  </div>
{/if}

{#if result}
  <div class="py-5 flex w-full justify-center items-center">
    <img
      src={`https://covers.openlibrary.org/b/isbn/${searchisbn}-M.jpg`}
      alt={result.title}
      class="hidden sm:block basis-1/4 h-72"
    />
    <div class="basis-3/4 flex flex-col md:flex-row justify-center px-2">
      <div
        class="basis-full md:basis-3/4 text-center md:text-left flex flex-col justify-center items-center gap-2 px-2 lg:px-5"
      >
        <div class="w-full">
          <span class="text-xl">Title / Name :</span>
          {result.title}
          <input type="text" class="hidden" value={result.title} name="name" />
        </div>
        <div class="w-full">
          <span class="text-xl">Author :</span>
          {result.by_statement}
          <input
            type="text"
            class="hidden"
            value={result.by_statement}
            name="author"
          />
        </div>
        <div class="w-full">
          <span class="text-xl">ISBN :</span>
          {result["isbn_13"]}
          <input
            type="text"
            class="hidden"
            value={result["isbn_13"]}
            name="isbn"
          />
        </div>
      </div>
      <div
        class="basis-full md:basis-1/4 flex justify-center items-center py-5"
      >
        <form
          method="POST"
          use:enhance={() => {
            return async ({ result, update }) => {
              if (result.type === "success") {
                toast.success("Book successfully added.");
                return goto(`/books`, { invalidateAll: true });
              }
              if (result.type === "failure") {
                toast.error("Something went wrong. Please try again.");
              }
            };
          }}
        >
          <input type="text" name="name" class="hidden" value={result.title} />
          <input
            type="text"
            name="author"
            class="hidden"
            value={result.by_statement}
          />
          <input
            type="text"
            name="isbn"
            class="hidden"
            value={result["isbn_13"]}
          />
          <input
            type="text"
            name="image"
            class="hidden"
            value={`https://covers.openlibrary.org/b/isbn/${searchisbn}-M.jpg`}
          />
          <Button type="submit">Add to Library</Button>
        </form>
      </div>
    </div>
  </div>
{:else if error && !searching}
  <div class="w-full text-center py-5">
    <h2 class="text-lg">No books found</h2>
  </div>
{/if}
