// client/app/routes/profile.tsx
import type { Route } from "./+types/profile";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import PageHeader from "~/components/PageHeader";
import { redirect, useFetcher } from "react-router";
import { Button } from "~/components/ui/button";
import { pb } from "~/lib/utils";
import { Switch } from "~/components/ui/switch";
import { toast } from "~/components/Toaster";
import { ZodError } from "zod";

export function meta({}: Route.MetaArgs) {
  return [{ title: "Profile" }, { name: "description", content: "Welcome to Homethings" }];
}

export async function clientLoader({}: Route.ClientLoaderArgs) {
  try {
    const user = pb.authStore.record;
    if (!user) {
      pb.authStore.clear();
      return redirect("/login");
    }
    const record = await pb.collection("users").getOne(user?.id as string);
    return { user: record };
  } catch (error) {
    console.error(error);
    return { user: null };
  }
}

export async function clientAction({ request }: Route.ClientActionArgs) {
  try {
    const formData = await request.formData();
    const name = formData.get("name");
    const showChat = formData.get("show_chat");
    const showNotes = formData.get("show_notes");
    const showTasks = formData.get("show_tasks");
    const user = pb.authStore.record;
    if (!user) {
      pb.authStore.clear();
      return redirect("/login");
    }
    await pb.collection("users").update(user?.id as string, {
      name,
      showChat: showChat === "on",
      showNotes: showNotes === "on",
      showTasks: showTasks === "on",
    });
    toast({
      description: "Profile updated",
      title: "Success",
    });
    return { ok: true, error: null };
  } catch (error) {
    if (error instanceof ZodError) {
      toast({
        description: error.errors[0].message,
        title: "Profile not updated",
        type: "destructive",
      });
      return { ok: false, error: error.errors[0].message };
    }
    return { ok: false, error: error as string };
  }
}

export default function Profile({ loaderData }: Route.ComponentProps) {
  const fetcher = useFetcher();
  const { user } = loaderData;
  return (
    <>
      <PageHeader title="Profile" subtitle="Manage your profile" />
      <fetcher.Form method="post" className="flex flex-col w-full max-w-xl items-center gap-4">
        <div className="grid w-full items-center gap-1.5">
          <Label htmlFor="email">Email</Label>
          <Input defaultValue={user?.email || ""} disabled />
        </div>
        <div className="grid w-full items-center gap-1.5">
          <Label htmlFor="name">Name</Label>
          <Input type="text" name="name" placeholder="Name" defaultValue={user?.name || ""} />
        </div>
        <div className="grid w-full grid-cols-1 lg:grid-cols-2 gap-4">
          <div className="w-full flex items-center justify-between">
            <Label htmlFor="show_chat">Show Chat</Label>
            <Switch defaultChecked={user?.showChat || false} id="show_chat" name="show_chat" />
          </div>
          <div className="w-full flex items-center justify-between">
            <Label htmlFor="show_notes">Show Notes</Label>
            <Switch defaultChecked={user?.showNotes || false} id="show_notes" name="show_notes" />
          </div>
          <div className="w-full flex items-center justify-between">
            <Label htmlFor="show_tasks">Show Tasks</Label>
            <Switch defaultChecked={user?.showTasks || false} id="show_tasks" name="show_tasks" />
          </div>
        </div>
        <div className="flex w-full items-center gap-1.5">
          <Button type="submit">Update</Button>
        </div>
      </fetcher.Form>
    </>
  );
}

// src/routes/(app)/profile/+page.svelte
<script lang="ts">
  import PageHeader from "@/lib/components/PageHeader.svelte";
  import { Button } from "@/lib/components/ui/button";
  import { Input } from "@/lib/components/ui/input";
  import { Label } from "@/lib/components/ui/label";
  import { Switch } from "@/lib/components/ui/switch";
  import type { PageServerData, ActionData } from "./$types";

  let { data, form }: { data: PageServerData; form: ActionData } = $props();
</script>

<svelte:head>
  <title>Profile | Homethings</title>
  <meta name="description" content="Manage your profile & account" />
</svelte:head>

<PageHeader
  title="Profile"
  subtitle="Change your profile picture or show/hide features to personalise your experience."
/>
<form
  method="POST"
  class="w-full flex flex-col justify-center items-center gap-2"
>
  <div class="w-full grid grid-cols-1 md:grid-cols-2 gap-5">
    <div class="w-full">
      <Label>Name:</Label>
      <Input
        class="my-2"
        type="text"
        placeholder="Name"
        name="name"
        value={data.user.name}
      />
    </div>
    <div class="w-full">
      <Label>Email:</Label>
      <Input class="my-2" type="text" value={data.user.email} disabled />
    </div>
  </div>
  <div class="w-full grid grid-cols-1 md:grid-cols-2 gap-5">
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Documents:</Label>
      </div>
      <Switch name="showDocuments" checked={data.user.showDocuments || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Notes:</Label>
      </div>
      <Switch name="showNotes" checked={data.user.showNotes || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Books:</Label>
      </div>
      <Switch name="showBooks" checked={data.user.showBooks || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Chat:</Label>
      </div>
      <Switch name="showChat" checked={data.user.showChat || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Wealth:</Label>
      </div>
      <Switch name="showWealth" checked={data.user.showWealth || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Tasks:</Label>
      </div>
      <Switch name="showTasks" checked={data.user.showTasks || false} />
    </div>
  </div>
  <div class="flex items-center justify-end w-full py-5 gap-2">
    {#if form?.success === false}
      <p class="text-theme">Error. Please try again.</p>
    {/if}
    <Button type="submit">Update</Button>
  </div>
</form>
