// client/app/routes/app/profile.tsx
import { redirect, useFetcher } from "react-router";
import { ZodError } from "zod";
import PageHeader from "~/components/PageHeader";
import { toast } from "~/components/Toaster";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { Switch } from "~/components/ui/switch";
import type { Route } from "./+types/profile";

export function meta() {
	return [
		{ title: "Profile | Homethings" },
		{ name: "description", content: "Welcome to Homethings" },
	];
}

export default function Profile({ loaderData }: Route.ComponentProps) {
	const fetcher = useFetcher();
	return (
		<>
			<PageHeader title="Profile" subtitle="Manage your profile" />
			<fetcher.Form
				method="post"
				className="flex flex-col w-full max-w-xl items-center gap-4 py-2"
			>
				<div className="grid w-full items-center gap-1.5">
					<Label htmlFor="email">Email</Label>
					<Input defaultValue="" disabled />
				</div>
				<div className="grid w-full items-center gap-1.5">
					<Label htmlFor="name">Name</Label>
					<Input type="text" name="name" placeholder="Name" defaultValue="" />
				</div>
				<div className="grid w-full grid-cols-1 lg:grid-cols-2 gap-4">
					<div className="w-full flex items-center justify-between">
						<Label htmlFor="show_chat">Show Chat</Label>
						<Switch defaultChecked={false} id="show_chat" name="show_chat" />
					</div>
					<div className="w-full flex items-center justify-between">
						<Label htmlFor="show_notes">Show Notes</Label>
						<Switch defaultChecked={false} id="show_notes" name="show_notes" />
					</div>
				</div>
				<div className="flex justify-end w-full gap-1.5">
					<Button type="submit">Update</Button>
				</div>
			</fetcher.Form>
		</>
	);
}

// src/routes/(app)/profile/+page.svelte
<script lang="ts">
  import PageHeader from "@/lib/components/PageHeader.svelte";
  import { Button } from "@/lib/components/ui/button";
  import { Input } from "@/lib/components/ui/input";
  import { Label } from "@/lib/components/ui/label";
  import { Switch } from "@/lib/components/ui/switch";
  import type { PageServerData, ActionData } from "./$types";

  let { data, form }: { data: PageServerData; form: ActionData } = $props();
</script>

<svelte:head>
  <title>Profile | Homethings</title>
  <meta name="description" content="Manage your profile & account" />
</svelte:head>

<PageHeader
  title="Profile"
  subtitle="Change your profile picture or show/hide features to personalise your experience."
/>
<form method="POST" class="w-full flex flex-col justify-center items-center gap-2">
  <div class="w-full grid grid-cols-1 md:grid-cols-2 gap-5">
    <div class="w-full">
      <Label>Name:</Label>
      <Input class="my-2" type="text" placeholder="Name" name="name" value={data.user.name} />
    </div>
    <div class="w-full">
      <Label>Email:</Label>
      <Input class="my-2" type="text" value={data.user.email} disabled />
    </div>
  </div>
  <div class="w-full grid grid-cols-1 md:grid-cols-2 gap-5">
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Documents:</Label>
      </div>
      <Switch name="showDocuments" checked={data.user.showDocuments || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Notes:</Label>
      </div>
      <Switch name="showNotes" checked={data.user.showNotes || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Books:</Label>
      </div>
      <Switch name="showBooks" checked={data.user.showBooks || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Chat:</Label>
      </div>
      <Switch name="showChat" checked={data.user.showChat || false} />
    </div>
    <div class="w-full flex justify-between items-center">
      <div>
        <Label>Show Wealth:</Label>
      </div>
      <Switch name="showWealth" checked={data.user.showWealth || false} />
    </div>
  </div>
  <div class="flex items-center justify-end w-full py-5 gap-2">
    {#if form?.success === false}
      <p class="text-theme">Error. Please try again.</p>
    {/if}
    <Button type="submit">Update</Button>
  </div>
</form>
