// src/pages/Chat.tsx
import { useEffect, useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import PageTitle from "@/components/PageTitle";
import PageHeader from "@/components/PageHeader";
import { getToken } from "@/lib/utils";

type Message = {
  role: string;
  content: string;
};

export default function Chat() {
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);

  const handleInputChange = (e: React.FormEvent<EventTarget>) => {
    const target = e.target as HTMLInputElement;
    setInput(target.value);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input) return;
    setLoading(true);
    setInput("");
    // Add the user input and an empty system message in one state update
    setMessages((currentMessages) => [
      ...currentMessages,
      { role: "user", content: input },
      { role: "system", content: "" }, // Placeholder for stream content
    ]);
    const systemMessageIndex = messages.length + 1; // +1 to account for the new user message

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: getToken() },
        body: JSON.stringify({ messages: [...messages, { role: "user", content: input }] }),
      });

      if (response.body) {
        const reader = response.body.getReader();
        const decoder = new TextDecoder();

        const readStream = async () => {
          let reading = true;
          while (reading) {
            const { done, value } = await reader.read();
            if (done) {
              reading = false;
              break;
            }
            const newText = decoder.decode(value, { stream: true });

            // Update the existing system message with new content
            setMessages((currentMessages) => {
              const updatedMessages = [...currentMessages];
              const existingMessage = updatedMessages[systemMessageIndex];
              updatedMessages[systemMessageIndex] = {
                ...existingMessage,
                content: existingMessage.content + newText,
              };
              return updatedMessages;
            });
          }
        };

        await readStream();
      }
    } catch (error) {
      console.error("Failed to send message:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setMessages([]);
  };

  useEffect(() => {
    // Autoscroll to the bottom of the chat as new messages are added
    const chat = document.getElementById("chat");
    if (chat) {
      chat.scrollTop = chat.scrollHeight;
    }
  }, [messages]);

  return (
    <div className="max-h-full">
      <PageTitle title="Chat | Homethings" />
      <PageHeader title="Chat" subtitle="AI powered chatbot" />
      <div className="flex flex-col h-[calc(100vh-210px)]">
        {messages.length === 0 ? (
          <div
            id="chat"
            className="flex w-full h-full items-center justify-center p-4 my-2 border border-zinc-700 rounded-lg">
            <h2>Your chat will appear here</h2>
          </div>
        ) : (
          <div id="chat" className="overflow-auto flex-grow p-4 my-2 border border-zinc-700 rounded-lg">
            {messages.map((m, index) => {
              const codeRegex = /```([\s\S]*?)```/;
              const match = m.content.match(codeRegex);

              if (match) {
                // Split message content from code
                const beforeCode = m.content.substring(0, match.index);
                const codeContent = match[1]; // The actual code without backticks
                const afterCode = m.content.substring((match?.index ?? 0) + (match?.[0]?.length ?? 0));

                return (
                  <div key={index} className="whitespace-pre-wrap py-1">
                    <span className="text-accent">{m.role === "user" ? "User: " : "AI: "}</span>
                    {beforeCode}
                    <div className="p-1 bg-zinc-100 text-black dark:bg-zinc-800 dark:text-white">
                      <pre>
                        <code>{codeContent}</code>
                      </pre>
                    </div>
                    {afterCode}
                  </div>
                );
              } else {
                // Render as normal if no code is detected
                return (
                  <div key={index} className="whitespace-pre-wrap py-1">
                    <span className="text-accent">{m.role === "user" ? "User: " : "AI: "}</span>
                    {m.content}
                  </div>
                );
              }
            })}
          </div>
        )}
        <form
          onSubmit={handleSubmit}
          className="flex space-y-2 md:space-x-5 md:space-y-0 flex-col md:flex-row">
          <Input
            type="text"
            value={input}
            placeholder="Chat to your assistant"
            onChange={handleInputChange}
          />
          <Button type="submit" disabled={loading}>
            {loading ? "Sending..." : "Submit"}
          </Button>
          <Button type="button" variant="secondary" onClick={handleReset}>
            Clear
          </Button>
        </form>
      </div>
    </div>
  );
}

// src/routes/(app)/chat/+page.svelte
<script lang="ts">
  import { Button } from "@/lib/components/ui/button";
  import { Input } from "@/lib/components/ui/input";
  import PageHeader from "@/lib/components/PageHeader.svelte";
  import { toast } from "svelte-sonner";
  let loading = $state(false);
  let input = $state("");
  let messages: Message[] = $state([]);
  type Message = {
    role: "user" | "assistant";
    content: string;
    type?: "code" | "text";
  };

  // Function to detect code in the streamed content
  function detectCodeBlock(text: string) {
    // Check for code block markers
    const hasCodeBlock = text.includes("```");
    const hasInlineCode = text.includes("`");

    if (hasCodeBlock) {
      // Extract content between ``` markers
      const codeBlockRegex = /```[\s\S]*?```/g;
      const matches = text.match(codeBlockRegex);
      if (matches) {
        return true;
      }
    }
    // Check for common code patterns if no explicit code blocks
    const codePatterns = [
      /{[\s\S]*?}/, // Curly braces blocks
      /function\s+\w+\s*\(/, // Function declarations
      /const|let|var\s+\w+\s*=/, // Variable declarations
      /<[\s\S]*?>/, // HTML tags
      /\b(if|for|while|switch|return)\b/, // Common programming keywords
    ];

    return codePatterns.some((pattern) => pattern.test(text));
  }

  // Function to extract and format code blocks
  function formatMessageWithCode(text: string) {
    // If no code blocks, return the text as is
    if (!text.includes("```")) {
      return text;
    }
    // Split the text into code and non-code parts
    const parts = text.split(/(```[\s\S]*?```)/);
    return parts
      .map((part) => {
        if (part.startsWith("```") && part.endsWith("```")) {
          // This is a code block - wrap in pre/code tags
          return `<pre class="bg-zinc-800 p-2 rounded-lg my-2"><code>${part.slice(3, -3)}</code></pre>`;
        }
        // This is regular text - return as is
        return part;
      })
      .join("");
  }

  async function handleCancel() {
    input = "";
    messages = [];
    loading = false;
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (input.trim() === "") {
      toast.error("Please enter a message to start using chat");
      return;
    }
    loading = true;
    messages = [...messages, { role: "user", content: input }];
    const userInput = input;
    input = "";

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messages: messages
            .slice(0, -1)
            .concat({ role: "user", content: userInput }),
        }),
      });

      if (!response.ok) throw new Error("Stream response was not ok");

      // Add assistant message that we'll stream into
      messages = [...messages, { role: "assistant", content: "" }];

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No reader available");

      const decoder = new TextDecoder();
      let currentMessage = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        // Decode the stream chunk and append to current message
        const chunk = decoder.decode(value);
        currentMessage += chunk;
        // Detect if the current accumulated message contains code
        const containsCode = detectCodeBlock(currentMessage);
        // Update the last message (assistant's message) with accumulated content
        messages = messages.map((msg, index) => {
          if (index === messages.length - 1) {
            return {
              ...msg,
              content: currentMessage,
              type: containsCode ? "code" : "text",
            };
          }
          return msg;
        });
      }
    } catch (error) {
      console.error("Error:", error);
      toast.error("Something went wrong");
    } finally {
      loading = false;
    }
  }
</script>

<svelte:head>
  <title>Chat | Homethings</title>
  <meta name="description" content="Your AI powered chatbot" />
</svelte:head>

<div class="max-h-full">
  <PageHeader title="Chat" subtitle="Your AI powered chatbot" />
  <div class="flex flex-col h-[calc(100vh-230px)]">
    {#if messages.length > 0}
      <div
        class="overflow-auto flex-grow p-4 my-2 border border-zinc-700 rounded-lg"
      >
        {#each messages as message}
          <div class="whitespace-pre-wrap py-1">
            <span class="text-theme"
              >{message.role === "user" ? "User: " : "AI: "}</span
            >
            {@html formatMessageWithCode(message.content)}
          </div>
        {/each}
      </div>
    {:else}
      <div
        class="flex w-full h-full items-center justify-center p-4 my-2 border border-zinc-700 rounded-lg"
      >
        <h2>Your chat will appear here</h2>
      </div>
    {/if}
    <form
      onsubmit={handleSubmit}
      class="flex space-y-2 md:space-x-5 md:space-y-0 flex-col md:flex-row"
    >
      <Input
        type="text"
        bind:value={input}
        placeholder="Chat to your assistant"
      />
      <Button type="submit" disabled={loading}>
        {loading ? "Sending..." : "Submit"}
      </Button>
      <Button onclick={handleCancel} type="button" variant="secondary"
        >Clear</Button
      >
    </form>
  </div>
</div>
