// src/routes/(app)/chat/+page.svelte
<script lang="ts">
  import { Button } from "@/lib/components/ui/button";
  import { Input } from "@/lib/components/ui/input";
  import PageHeader from "@/lib/components/PageHeader.svelte";
  import { toast } from "svelte-sonner";
  let loading = $state(false);
  let input = $state("");
  let messages: Message[] = $state([]);
  type Message = {
    role: "user" | "assistant";
    content: string;
    type?: "code" | "text";
  };

  import * as Select from "$lib/components/ui/select/index.js";

  const models = [
    { value: "default", label: "ChatGPT 4" },
    { value: "svelte", label: "Svelte" },
  ];

  let selectedModel = $state(models[0].value || "");

  // Function to detect code in the streamed content
  function detectCodeBlock(text: string) {
    // Check for code block markers
    const hasCodeBlock = text.includes("```");
    const hasInlineCode = text.includes("`");

    if (hasCodeBlock) {
      // Extract content between ``` markers
      const codeBlockRegex = /```[\s\S]*?```/g;
      const matches = text.match(codeBlockRegex);
      if (matches) {
        return true;
      }
    }
    // Check for common code patterns if no explicit code blocks
    const codePatterns = [
      /{[\s\S]*?}/, // Curly braces blocks
      /function\s+\w+\s*\(/, // Function declarations
      /const|let|var\s+\w+\s*=/, // Variable declarations
      /<[\s\S]*?>/, // HTML tags
      /\b(if|for|while|switch|return)\b/, // Common programming keywords
    ];

    return codePatterns.some((pattern) => pattern.test(text));
  }

  // Function to extract and format code blocks
  function formatMessageWithCode(text: string) {
    // If no code blocks, return the text as is
    if (!text.includes("```")) {
      return text;
    }
    // Split the text into code and non-code parts
    const parts = text.split(/(```[\s\S]*?```)/);
    return parts
      .map((part) => {
        if (part.startsWith("```") && part.endsWith("```")) {
          // This is a code block - wrap in pre/code tags
          return `<pre class="bg-zinc-800 p-2 rounded-lg my-2"><code>${part.slice(3, -3)}</code></pre>`;
        }
        // This is regular text - return as is
        return part;
      })
      .join("");
  }

  async function handleCancel() {
    input = "";
    messages = [];
    loading = false;
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (input.trim() === "") {
      toast.error("Please enter a message to start using chat");
      return;
    }
    loading = true;
    messages = [...messages, { role: "user", content: input }];
    const userInput = input;
    input = "";
    let endpoint = "/api/chat";
    if (selectedModel === "svelte") {
      endpoint = "/api/chat/svelte";
    }

    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messages: messages
            .slice(0, -1)
            .concat({ role: "user", content: userInput }),
        }),
      });

      if (!response.ok) throw new Error("Stream response was not ok");

      // Add assistant message that we'll stream into
      messages = [...messages, { role: "assistant", content: "" }];

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No reader available");

      const decoder = new TextDecoder();
      let currentMessage = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        // Decode the stream chunk and append to current message
        const chunk = decoder.decode(value);
        currentMessage += chunk;
        // Detect if the current accumulated message contains code
        const containsCode = detectCodeBlock(currentMessage);
        // Update the last message (assistant's message) with accumulated content
        messages = messages.map((msg, index) => {
          if (index === messages.length - 1) {
            return {
              ...msg,
              content: currentMessage,
              type: containsCode ? "code" : "text",
            };
          }
          return msg;
        });
      }
    } catch (error) {
      console.error("Error:", error);
      toast.error("Something went wrong");
    } finally {
      loading = false;
    }
  }
</script>

<svelte:head>
  <title>Chat | Homethings</title>
  <meta name="description" content="Your AI powered chatbot" />
</svelte:head>

<div class="max-h-full">
  <PageHeader title="Chat" subtitle="Your AI powered chatbot" />
  <div class="flex justify-end w-full py-2">
    <Select.Root type="single" name="chatModel" bind:value={selectedModel}>
      <Select.Trigger class="w-40">
        {models.find((model) => model.value === selectedModel)?.label}
      </Select.Trigger>
      <Select.Content>
        <Select.Group>
          {#each models as model}
            <Select.Item value={model.value} label={model.value}>
              {model.label}
            </Select.Item>
          {/each}
        </Select.Group>
      </Select.Content>
    </Select.Root>
  </div>
  <div class="flex flex-col h-[calc(100vh-230px)]">
    {#if messages.length > 0}
      <div
        class="overflow-auto flex-grow p-4 my-2 border border-zinc-700 rounded-lg"
      >
        {#each messages as message}
          <div class="whitespace-pre-wrap py-1">
            <span class="text-theme"
              >{message.role === "user" ? "User: " : "AI: "}</span
            >
            {@html formatMessageWithCode(message.content)}
          </div>
        {/each}
      </div>
    {:else}
      <div
        class="flex w-full h-full items-center justify-center p-4 my-2 border border-zinc-700 rounded-lg"
      >
        <h2>Your chat will appear here</h2>
      </div>
    {/if}
    <form
      onsubmit={handleSubmit}
      class="flex space-y-2 md:space-x-5 md:space-y-0 flex-col md:flex-row"
    >
      <Input
        type="text"
        bind:value={input}
        placeholder="Chat to your assistant"
      />
      <Button type="submit" disabled={loading}>
        {loading ? "Sending..." : "Submit"}
      </Button>
      <Button onclick={handleCancel} type="button" variant="secondary"
        >Clear</Button
      >
    </form>
  </div>
</div>

// client/app/routes/app/chat.tsx
import { useEffect, useRef, useState } from "react";
import { useLoaderData } from "react-router";
import { toast } from "sonner";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "~/components/ui/select";
import {
	type ChatMessage,
	getAvailableModels,
	streamChatMessage,
} from "~/lib/chat";

export function meta() {
	return [
		{ title: "Chat | Homethings" },
		{ name: "description", content: "Chat with AI" },
	];
}

export async function clientLoader() {
	try {
		const { models, default: defaultModel } = await getAvailableModels();
		return { models, defaultModel };
	} catch {
		return { models: [] as string[], defaultModel: "" };
	}
}

export default function Chat() {
	const loaderData = useLoaderData<typeof clientLoader>();
	const [messages, setMessages] = useState<ChatMessage[]>([]);
	const [input, setInput] = useState("");
	const [isLoading, setIsLoading] = useState(false);
	const [selectedModel, setSelectedModel] = useState<string>("");
	const messagesEndRef = useRef<HTMLDivElement>(null);
	const inputRef = useRef<HTMLInputElement>(null);
	const messageIdRef = useRef(0);

	const models = loaderData?.models ?? [];
	const defaultModel = loaderData?.defaultModel ?? "";

	useEffect(() => {
		if (defaultModel && !selectedModel) {
			setSelectedModel(defaultModel);
		}
	}, [defaultModel, selectedModel]);

	useEffect(() => {
		if (messages.length > 0) {
			messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
		}
	}, [messages.length]);

	async function handleSendMessage() {
		if (!input.trim() || isLoading) return;

		const userMessageId = ++messageIdRef.current;
		const userMessage: ChatMessage = {
			id: userMessageId,
			role: "user",
			content: input,
		};
		setMessages((prev) => [...prev, userMessage]);
		setInput("");
		setIsLoading(true);

		let streamError: Error | null = null;

		try {
			const response = await streamChatMessage(
				[...messages, userMessage],
				selectedModel || undefined,
			);

			const reader = response.body?.getReader();
			const decoder = new TextDecoder();

			if (!reader) {
				throw new Error("Response body is not readable");
			}

			let assistantMessage = "";
			const assistantMessageId = ++messageIdRef.current;
			const assistantMsg: ChatMessage = {
				id: assistantMessageId,
				role: "assistant",
				content: "",
			};
			setMessages((prev) => [...prev, assistantMsg]);

			while (true) {
				let result: ReadableStreamReadResult<Uint8Array>;
				try {
					result = await reader.read();
				} catch (readError) {
					streamError =
						readError instanceof Error
							? readError
							: new Error(String(readError));
					break;
				}

				const { done, value } = result;
				if (done) break;

				const chunk = decoder.decode(value, { stream: true });

				if (chunk.toLowerCase().includes("error") || chunk.includes("{")) {
					try {
						const parsed = JSON.parse(chunk);
						if (parsed.error) {
							streamError = new Error(parsed.error);
							break;
						}
					} catch {
						// Not JSON, treat as regular text
					}
				}

				assistantMessage += chunk;
				setMessages((prev) => {
					const updated = [...prev];
					const lastMsg = updated[updated.length - 1];
					if (lastMsg?.role === "assistant") {
						lastMsg.content = assistantMessage;
					}
					return updated;
				});
			}
		} catch (error) {
			console.error("Chat error:", error);
			streamError =
				error instanceof Error ? error : new Error("Failed to send message");
		} finally {
			setIsLoading(false);

			if (streamError) {
				setMessages((prev) => {
					const updated = [...prev];
					if (
						updated[updated.length - 1]?.role === "assistant" &&
						updated[updated.length - 1]?.content === ""
					) {
						updated.pop();
					}
					return updated;
				});
				toast.error(streamError.message);
			}

			inputRef.current?.focus();
		}
	}

	function handleKeyDown(e: React.KeyboardEvent) {
		if (e.key === "Enter" && !e.shiftKey) {
			e.preventDefault();
			handleSendMessage();
		}
	}

	return (
		<div className="flex flex-col h-full px-2 mx-auto">
			<div className="flex items-center gap-4 pb-4">
				<span className="text-sm text-muted-foreground">Model:</span>
				<Select value={selectedModel} onValueChange={setSelectedModel}>
					<SelectTrigger className="w-[200px]">
						<SelectValue placeholder="Select model" />
					</SelectTrigger>
					<SelectContent>
						{models.map((model) => (
							<SelectItem key={model} value={model}>
								{model}
							</SelectItem>
						))}
					</SelectContent>
				</Select>
			</div>

			<div className="flex-1 max-h-[80vh] md:max-h-[72vh] overflow-y-auto space-y-4 p-4 border rounded-lg bg-card/50">
				{messages.length === 0 && (
					<div className="flex items-center justify-center h-full">
						<p className="text-muted-foreground">
							Start a conversation with the AI
						</p>
					</div>
				)}
				{messages.map((msg) => (
					<div
						key={msg.id}
						className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
					>
						<div
							className={`max-w-[80%] rounded-lg px-4 py-2 ${
								msg.role === "user" ? "bg-theme text-white" : "bg-muted"
							}`}
						>
							<div className="text-sm font-medium mb-1">
								{msg.role === "user" ? "You" : "Assistant"}
							</div>
							<div className="whitespace-pre-wrap">{msg.content}</div>
						</div>
					</div>
				))}
				{isLoading && (
					<div className="flex justify-start">
						<div className="bg-muted rounded-lg px-4 py-2">
							<div className="text-sm font-medium mb-1">Assistant</div>
							<div className="flex items-center gap-2">
								<span className="animate-pulse">Thinking...</span>
							</div>
						</div>
					</div>
				)}
				<div ref={messagesEndRef} />
			</div>

			<div className="pt-4 flex gap-2">
				<Input
					ref={inputRef}
					value={input}
					onChange={(e) => setInput(e.target.value)}
					onKeyDown={handleKeyDown}
					placeholder="Type a message..."
					disabled={isLoading}
					className="flex-1"
				/>
				<Button
					onClick={handleSendMessage}
					disabled={isLoading || !input.trim()}
				>
					{isLoading ? "Sending..." : "Send"}
				</Button>
			</div>
		</div>
	);
}
