// src/routes/(app)/chat/+page.svelte
<script lang="ts">
  import { Button } from "@/lib/components/ui/button";
  import { Input } from "@/lib/components/ui/input";
  import PageHeader from "@/lib/components/PageHeader.svelte";
  import { toast } from "svelte-sonner";
  let loading = $state(false);
  let input = $state("");
  let messages: Message[] = $state([]);
  type Message = {
    role: "user" | "assistant";
    content: string;
    type?: "code" | "text";
  };

  // Function to detect code in the streamed content
  function detectCodeBlock(text: string) {
    // Check for code block markers
    const hasCodeBlock = text.includes("```");
    const hasInlineCode = text.includes("`");

    if (hasCodeBlock) {
      // Extract content between ``` markers
      const codeBlockRegex = /```[\s\S]*?```/g;
      const matches = text.match(codeBlockRegex);
      if (matches) {
        return true;
      }
    }
    // Check for common code patterns if no explicit code blocks
    const codePatterns = [
      /{[\s\S]*?}/, // Curly braces blocks
      /function\s+\w+\s*\(/, // Function declarations
      /const|let|var\s+\w+\s*=/, // Variable declarations
      /<[\s\S]*?>/, // HTML tags
      /\b(if|for|while|switch|return)\b/, // Common programming keywords
    ];

    return codePatterns.some((pattern) => pattern.test(text));
  }

  // Function to extract and format code blocks
  function formatMessageWithCode(text: string) {
    // If no code blocks, return the text as is
    if (!text.includes("```")) {
      return text;
    }
    // Split the text into code and non-code parts
    const parts = text.split(/(```[\s\S]*?```)/);
    return parts
      .map((part) => {
        if (part.startsWith("```") && part.endsWith("```")) {
          // This is a code block - wrap in pre/code tags
          return `<pre class="bg-zinc-800 p-2 rounded-lg my-2"><code>${part.slice(3, -3)}</code></pre>`;
        }
        // This is regular text - return as is
        return part;
      })
      .join("");
  }

  async function handleCancel() {
    input = "";
    messages = [];
    loading = false;
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (input.trim() === "") {
      toast.error("Please enter a message to start using chat");
      return;
    }
    loading = true;
    messages = [...messages, { role: "user", content: input }];
    const userInput = input;
    input = "";

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messages: messages
            .slice(0, -1)
            .concat({ role: "user", content: userInput }),
        }),
      });

      if (!response.ok) throw new Error("Stream response was not ok");

      // Add assistant message that we'll stream into
      messages = [...messages, { role: "assistant", content: "" }];

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No reader available");

      const decoder = new TextDecoder();
      let currentMessage = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        // Decode the stream chunk and append to current message
        const chunk = decoder.decode(value);
        currentMessage += chunk;
        // Detect if the current accumulated message contains code
        const containsCode = detectCodeBlock(currentMessage);
        // Update the last message (assistant's message) with accumulated content
        messages = messages.map((msg, index) => {
          if (index === messages.length - 1) {
            return {
              ...msg,
              content: currentMessage,
              type: containsCode ? "code" : "text",
            };
          }
          return msg;
        });
      }
    } catch (error) {
      console.error("Error:", error);
      toast.error("Something went wrong");
    } finally {
      loading = false;
    }
  }
</script>

<svelte:head>
  <title>Chat | Homethings</title>
  <meta name="description" content="Your AI powered chatbot" />
</svelte:head>

<div class="max-h-full">
  <PageHeader title="Chat" subtitle="Your AI powered chatbot" />
  <div class="flex flex-col h-[calc(100vh-230px)]">
    {#if messages.length > 0}
      <div
        class="overflow-auto flex-grow p-4 my-2 border border-zinc-700 rounded-lg"
      >
        {#each messages as message}
          <div class="whitespace-pre-wrap py-1">
            <span class="text-theme"
              >{message.role === "user" ? "User: " : "AI: "}</span
            >
            {@html formatMessageWithCode(message.content)}
          </div>
        {/each}
      </div>
    {:else}
      <div
        class="flex w-full h-full items-center justify-center p-4 my-2 border border-zinc-700 rounded-lg"
      >
        <h2>Your chat will appear here</h2>
      </div>
    {/if}
    <form
      onsubmit={handleSubmit}
      class="flex space-y-2 md:space-x-5 md:space-y-0 flex-col md:flex-row"
    >
      <Input
        type="text"
        bind:value={input}
        placeholder="Chat to your assistant"
      />
      <Button type="submit" disabled={loading}>
        {loading ? "Sending..." : "Submit"}
      </Button>
      <Button onclick={handleCancel} type="button" variant="secondary"
        >Clear</Button
      >
    </form>
  </div>
</div>

// client/app/routes/chat.tsx
import { useState } from "react";
import type { Route } from "./+types/chat";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "~/components/ui/popover";
import { Card, CardContent, CardFooter, CardHeader } from "~/components/ui/card";
import { SiGooglegemini, SiOpenai } from "react-icons/si";
import { Bot } from "lucide-react";
import { toast } from "~/components/Toaster";
import useWindowSize from "~/hooks/use-windowsize";
import PocketBase from "pocketbase";
const pb = new PocketBase(import.meta.env.VITE_POCKETBASE_URL);

type Message = {
  role: "user" | "assistant";
  content: string;
};

export function meta({}: Route.MetaArgs) {
  return [{ title: "Chat" }, { name: "description", content: "Welcome to Homethings" }];
}

export async function clientLoader({}: Route.ClientLoaderArgs) {
  try {
    const user = pb.authStore.record;
    if (!user) {
      pb.authStore.clear();
      return redirect("/login");
    }
    const keys = await pb.send("/api/keys", {});
    return { keys };
  } catch (error) {
    console.error(error);
    return { keys: null };
  }
}

export default function Chat({ loaderData }: Route.ComponentProps) {
  const { keys } = loaderData;
  const { width } = useWindowSize();
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [streamingMessage, setStreamingMessage] = useState("");
  const [chatModel, setChatModel] = useState("openai/gpt-4o-mini");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!input.trim() || isLoading || !chatModel) {
      toast({
        title: "Error",
        description: "Please enter a message",
        type: "destructive",
      });
      return;
    }

    // Add user message
    const userMessage: Message = { role: "user", content: input };
    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);
    setStreamingMessage("");

    try {
      const response = await fetch(`${import.meta.env.VITE_WEBILITI_BASE_URL}/system/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Webiliti-System-Key": keys.webiliti },
        body: JSON.stringify({ model: chatModel, messages: [{ role: "user", content: input }] }),
      });
      console.log(response);
      if (!response.ok) throw new Error("Failed to send message");

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No reader available");

      let fullMessage = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const text = new TextDecoder().decode(value);
        try {
          const lines = text.split("\n").filter((line) => line.trim());
          for (const line of lines) {
            const content = line.startsWith("data: ") ? line.slice(6) : line;
            fullMessage += content;
            setStreamingMessage(fullMessage);
          }
        } catch (e) {
          console.error("Error processing chunk:", e);
          fullMessage += text;
          setStreamingMessage(fullMessage);
        }
      }

      // Add assistant's message to the chat
      setMessages((prev) => [...prev, { role: "assistant", content: fullMessage }]);
    } catch (error) {
      console.error("Chat error:", error);
    } finally {
      setIsLoading(false);
    }
  }

  if (!keys) {
    toast({
      title: "Error",
      description: "Failed to start chat service",
      type: "destructive",
    });
    return null;
  }

  return (
    <div className="w-full mx-auto p-4 flex flex-col h-[calc(100vh-8rem)]">
      <div className="flex-1 overflow-y-auto space-y-4 mb-4">
        {messages.map((message, i) => (
          <div
            key={i}
            className={`p-4 rounded-lg text-white ${
              message.role === "user"
                ? "bg-theme/90 dark:bg-theme/50 ml-auto max-w-[80%]"
                : "bg-zinc-900 mr-auto max-w-[80%]"
            }`}>
            {message.content}
          </div>
        ))}
        {isLoading && streamingMessage && (
          <div className="bg-zinc-900 text-white p-4 rounded-lg mr-auto max-w-[80%]">{streamingMessage}</div>
        )}
      </div>

      <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-2">
        <div className="w-full">
          <Input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Type your message..."
            className="w-full"
            disabled={isLoading}
          />
        </div>
        <div className="flex w-full sm:w-auto gap-2">
          <Popover>
            <PopoverTrigger asChild>
              <Button variant="outline" className="flex-1 sm:flex-initial">
                <Bot className="size-4" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-full my-2" align={width < 640 ? "start" : "end"}>
              <div className="w-full pb-2">
                <h4 className="font-medium leading-none">Model</h4>
                <p className="text-sm text-muted-foreground">Set the model for the chat.</p>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {modelList.map((model) => (
                  <ModelCard
                    key={model.value}
                    model={model}
                    onClick={() => setChatModel(model.value)}
                    selected={model.value === chatModel}
                  />
                ))}
              </div>
            </PopoverContent>
          </Popover>
          <Button type="submit" disabled={isLoading} className="flex-1 sm:flex-initial">
            {isLoading ? "Sending..." : "Send"}
          </Button>
          <Button variant="outline" asChild>
            <div onClick={() => setMessages([])} className="flex-1 sm:flex-initial cursor-pointer">
              Clear
            </div>
          </Button>
        </div>
      </form>
    </div>
  );
}

const modelList = [
  { name: "GPT", variant: "4o-mini", value: "openai/gpt-4o-mini", icon: SiOpenai },
  { name: "GPT", variant: "4o", value: "openai/gpt-4o", icon: SiOpenai },
  {
    name: "Gemini",
    variant: "2.0-flash-lite",
    value: "google/gemini-2.0-flash-lite-001",
    icon: SiGooglegemini,
  },
  { name: "Gemini", variant: "2.0-flash", value: "google/gemini-2.0-flash-001", icon: SiGooglegemini },
];

type Model = {
  name: string;
  variant: string;
  value: string;
  icon: React.ComponentType;
};

function ModelCard({ model, onClick, selected }: { model: Model; onClick: () => void; selected: boolean }) {
  const Icon = model.icon;
  return (
    <Card
      className={`w-full flex flex-col items-center justify-between cursor-pointer ${
        selected ? "border-zinc-900 dark:border-zinc-50" : ""
      }`}
      onClick={onClick}>
      <CardHeader className="flex items-center justify-center">
        <div className="text-4xl">
          <Icon />
        </div>
      </CardHeader>
      <CardContent className="flex flex-col items-center justify-center">
        <p className="py-1">{model.name}</p>
        <p className="py-1 text-sm text-muted-foreground">{model.variant}</p>
      </CardContent>
      <CardFooter className="flex items-center justify-center"></CardFooter>
    </Card>
  );
}
function redirect(arg0: string) {
  throw new Error("Function not implemented.");
}
