// client/app/components/BreadcrumbNav.tsx
import React from "react";
import { Link, useLocation } from "react-router";
import {
	Breadcrumb,
	BreadcrumbItem,
	BreadcrumbLink,
	BreadcrumbList,
	BreadcrumbPage,
	BreadcrumbSeparator,
} from "~/components/ui/breadcrumb";

export function BreadcrumbNav() {
	const location = useLocation();

	const pathSegments = location.pathname.split("/").filter((segment) => {
		return segment !== "" && segment !== "app";
	});

	return (
		<Breadcrumb className="hidden md:flex">
			<BreadcrumbList className="my-3 ml-3">
				<BreadcrumbItem>
					<BreadcrumbLink asChild>
						<Link to="/app">Home</Link>
					</BreadcrumbLink>
				</BreadcrumbItem>
				{pathSegments.map((segment, index) => {
					const path = `/${pathSegments.slice(0, index + 1).join("/")}`;
					const isLast = index === pathSegments.length - 1;

					return (
						<React.Fragment key={path}>
							<BreadcrumbSeparator />
							<BreadcrumbItem>
								{isLast ? (
									<BreadcrumbPage>
										{segment.charAt(0).toUpperCase() + segment.slice(1)}
									</BreadcrumbPage>
								) : (
									<BreadcrumbLink asChild>
										<Link to={"/app" + path}>
											{segment.charAt(0).toUpperCase() + segment.slice(1)}
										</Link>
									</BreadcrumbLink>
								)}
							</BreadcrumbItem>
						</React.Fragment>
					);
				})}
			</BreadcrumbList>
		</Breadcrumb>
	);
}

// src/lib/components/BreadcrumbNav.svelte
<script lang="ts">
  import * as Breadcrumb from "$lib/components/ui/breadcrumb/index.js";
  import { page } from "$app/stores";
  let paths = $derived.by(() => {
    return $page.url.pathname.split("/").filter((path) => path !== "");
  });
</script>

<Breadcrumb.Root class="my-3 ml-3">
  <Breadcrumb.List>
    <Breadcrumb.Item>
      <Breadcrumb.Link href="/">Home</Breadcrumb.Link>
    </Breadcrumb.Item>
    {#each paths as path, index}
      <Breadcrumb.Separator />
      <Breadcrumb.Item>
        <Breadcrumb.Link href={paths.slice(0, index + 1).join("/")} class="capitalize">
          {path}
        </Breadcrumb.Link>
      </Breadcrumb.Item>
    {/each}
  </Breadcrumb.List>
</Breadcrumb.Root>
