// client/app/components/Navbar.tsx
import {
  Home,
  House,
  Bot,
  NotebookPen,
  Menu,
  User as UserIcon,
  X,
} from "lucide-react";
import { useEffect, useRef } from "react";
import { Link } from "react-router";
import { ModeToggle } from "~/components/theme-toggle";
import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "~/components/ui/sidebar";
import type { User } from "~/lib/schema";

export function Navbar({ user }: { user: User | null }) {
  const { toggleSidebar } = useSidebar();

  return (
    <>
      <AppSidebar user={user} />
      <div className="flex min-h-12 md:min-h-16 items-center px-4 md:px-6 py-0 md:py-1">
        <Menu
          onClick={toggleSidebar}
          className="h-[1.4rem] w-[1.4rem] lg:hidden cursor-pointer"
        />
        <Link
          className="text-theme justify-center items-center gap-2 hidden lg:flex"
          to="/app"
        >
          <House className="h-[1.4rem] w-[1.4rem]" />
          <p>Homethings</p>
        </Link>
        <div className="text-theme capitalize justify-center items-center gap-2 flex lg:hidden mx-1">
          Homethings
        </div>
        <div className="ml-auto flex items-center space-x-4">
          <ModeToggle />
          <DropdownMenu>
            <DropdownMenuTrigger asChild className="hover:cursor-pointer">
              <Avatar>
                <AvatarImage src={user?.avatar} alt={user?.name} />
                <AvatarFallback>{user?.name?.slice(0, 1)}</AvatarFallback>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="min-w-[12rem]">
              <DropdownMenuLabel>
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-medium leading-none">
                    {user?.name}
                  </p>
                  <p className="text-xs leading-none text-muted-foreground">
                    {user?.email}
                  </p>
                </div>
              </DropdownMenuLabel>
              <DropdownMenuSeparator />
              <Link to="/app/profile">
                <DropdownMenuItem className="hover:cursor-pointer">
                  Profile
                </DropdownMenuItem>
              </Link>
              <Link to="/app/feedback">
                <DropdownMenuItem className="hover:cursor-pointer">
                  Feedback
                </DropdownMenuItem>
              </Link>
              <Link to="/app/logout">
                <DropdownMenuItem className="hover:cursor-pointer">
                  Logout
                </DropdownMenuItem>
              </Link>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </>
  );
}

// Menu items.
export const menuItems = [
  {
    title: "Dashboard",
    url: "/app",
    icon: Home,
  },
  {
    title: "Chat",
    url: "/app/chat",
    icon: Bot,
  },
  {
    title: "Notes",
    url: "/app/notes",
    icon: NotebookPen,
  },
  {
    title: "Profile",
    url: "/app/profile",
    icon: UserIcon,
  },
];

function AppSidebar({ user }: { user: User | null }) {
  const { toggleSidebar, setOpen } = useSidebar();
  const sidebarRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setOpen(false);
      }
    };
    const handleClickOutside = (event: MouseEvent) => {
      if (
        sidebarRef.current &&
        !sidebarRef.current.contains(event.target as Node)
      ) {
        setOpen(false);
      }
    };
    document.addEventListener("keydown", handleEscape);
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("keydown", handleEscape);
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [setOpen]);

  return (
    <Sidebar ref={sidebarRef} variant="floating" collapsible="offcanvas">
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel className="flex justify-end">
            <X
              onClick={toggleSidebar}
              className="h-[1.4rem] w-[1.4rem] cursor-pointer hover:text-theme"
            />
          </SidebarGroupLabel>
          <SidebarHeader>
            <h1>What do you want to do?</h1>
          </SidebarHeader>
          <SidebarGroupContent>
            <SidebarMenu>
              <nav className="my-5 flex flex-col space-y-3">
                {menuItems.map((item) => {
                  if (
                    (item.title === "Notes" && !user?.showNotes) ||
                    (item.title === "Chat" && !user?.showChat)
                  ) {
                    return null;
                  }
                  return (
                    <SidebarMenuItem key={item.title}>
                      <SidebarMenuButton asChild>
                        <Link to={item.url}>
                          <item.icon />
                          <span>{item.title}</span>
                        </Link>
                      </SidebarMenuButton>
                    </SidebarMenuItem>
                  );
                })}
              </nav>
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
    </Sidebar>
  );
}

// src/lib/components/NavBar.svelte
<script lang="ts">
  import House from "lucide-svelte/icons/house";
  import MenuIcon from "lucide-svelte/icons/menu";
  import * as Sheet from "$lib/components/ui/sheet/index.js";
  import DarkModeToggle from "./DarkModeToggle.svelte";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import * as Avatar from "$lib/components/ui/avatar/index.js";
  import type { SelectUser } from "$lib/server/db/schema";
  let { user }: { user: SelectUser } = $props();
</script>

<div class="border-b">
  <div class="flex h-16 items-center px-6">
    <Sheet.Root>
      <Sheet.Trigger>
        <MenuIcon class="h-[1.4rem] w-[1.4rem] lg:hidden cursor-pointer" />
      </Sheet.Trigger>
      <a class="text-theme justify-center items-center gap-2 hidden lg:flex" href="/">
        <House class="h-[1.4rem] w-[1.4rem]" />
        <p>Homethings</p>
      </a>
      <div class="ml-auto flex items-center space-x-4">
        <DarkModeToggle />
        <DropdownMenu.Root>
          <DropdownMenu.Trigger>
            <Avatar.Root>
              <Avatar.Image src={user.profileImage} alt={user.name || "User Profile"} />
              <Avatar.Fallback>{user.name?.charAt(0) || "??"}</Avatar.Fallback>
            </Avatar.Root>
          </DropdownMenu.Trigger>
          <DropdownMenu.Content align="end" class="min-w-[12rem]">
            <DropdownMenu.Group>
              <DropdownMenu.GroupHeading>
                <div class="flex flex-col space-y-1">
                  <p class="text-sm font-medium leading-none">{user.name || "--"}</p>
                  <p class="text-xs leading-none text-muted-foreground">{user.email || ""}</p>
                </div>
              </DropdownMenu.GroupHeading>
              <DropdownMenu.Separator />
              <a href="/profile">
                <DropdownMenu.Item class="hover:cursor-pointer">Profile</DropdownMenu.Item>
              </a>
              <a href="/feedback">
                <DropdownMenu.Item class="hover:cursor-pointer">Feedback</DropdownMenu.Item>
              </a>
              <a href="/logout">
                <DropdownMenu.Item class="hover:cursor-pointer">Logout</DropdownMenu.Item>
              </a>
            </DropdownMenu.Group>
          </DropdownMenu.Content>
        </DropdownMenu.Root>
      </div>
      <Sheet.Content side="left">
        <Sheet.Header>
          <Sheet.Title>What do you want to do?</Sheet.Title>
          <nav class="py-10 flex flex-col space-y-4">
            <a href="/" class="text-sm hover:text-theme dark:text-white dark:hover:text-theme"> Home </a>
            {#if user.showChat}
              <a href="/chat" class="text-sm hover:text-theme dark:text-white dark:hover:text-theme">
                Chat
              </a>
            {/if}
            {#if user.showNotes}
              <a href="/notes" class="text-sm hover:text-theme dark:text-white dark:hover:text-theme">
                Notes
              </a>
            {/if}
            {#if user.showDocuments}
              <a href="/documents" class="text-sm hover:text-theme dark:text-white dark:hover:text-theme">
                Documents
              </a>
            {/if}
            {#if user.showBooks}
              <a href="/books" class="text-sm hover:text-theme dark:text-white dark:hover:text-theme">
                Books
              </a>
            {/if}
            <a href="/profile" class="text-sm hover:text-theme dark:text-white dark:hover:text-theme">
              Profile
            </a>
          </nav>
        </Sheet.Header>
      </Sheet.Content>
    </Sheet.Root>
  </div>
</div>
