// src/pages/Documents.tsx
import PageHeader from "@/components/PageHeader";
import PageTitle from "@/components/PageTitle";
import { useLoaderData } from "react-router-dom";
import { Document } from "@/types";
import { DocumentsTable } from "@/components/DocumentsTable";
import UploadForm from "@/components/DocumentUpload";

type LoadedData = {
  count: number;
  data: Document[];
};

export default function Documents() {
  const LoadedData = useLoaderData() as LoadedData;
  return (
    <>
      <PageTitle title="Documents | Homethings" />
      <PageHeader title="Documents" subtitle="Document storage shared across your account with all members" />
      <div className="w-full">
        <DocumentsTable data={LoadedData.data} />
        <div className="py-5">
          <h3 className="py-4 text-xl">Upload a new document</h3>
          <UploadForm />
        </div>
      </div>
    </>
  );
}

// src/routes/(app)/documents/+page.svelte
<script lang="ts">
  import PageHeader from "@/lib/components/PageHeader.svelte";
  import DocumentsTable from "./DocumentsTable.svelte";
  import { columns } from "./columns";
  import type { PageData } from "./$types";
  import UploadForm from "./UploadForm.svelte";

  export let data: PageData;
</script>

<svelte:head>
  <title>Documents | Homethings</title>
  <meta
    name="description"
    content="Document storage shared across your account"
  />
</svelte:head>

<PageHeader
  title="Documents"
  subtitle="Document storage shared across your account"
/>
<DocumentsTable data={data.documents} {columns} />
<UploadForm />
